/* Automatically generated by './build/bin/build-entry.js' */

import Alert from './components/alert'
import Aside from './components/aside'
import Container from './components/container'
import Header from './components/header'
import Footer from './components/footer'
import Main from './components/main'
import Row from './components/row'
import Col from './components/col'
import ButtonGroup from './components/button-group'
import Button from './components/button'
import Radio from './components/radio'
import RadioButton from './components/radio-button'
import RadioGroup from './components/radio-group'
import Checkbox from './components/checkbox'
import CheckboxButton from './components/checkbox-button'
import CheckboxGroup from './components/checkbox-group'

const components = [
  Alert,
  Aside,
  Container,
  Header,
  Footer,
  Main,
  Row,
  Col,
  ButtonGroup,
  Button,
  Radio,
  RadioButton,
  RadioGroup,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
]

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  }
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  Alert,
  Aside,
  Container,
  Header,
  Footer,
  Main,
  Row,
  Col,
  ButtonGroup,
  Button,
  Radio,
  RadioButton,
  RadioGroup,
  Checkbox,
  CheckboxButton,
  CheckboxGroup
}
