/* Automatically generated by './build/bin/build-entry.js' */

import Alert from './components/alert'
import Aside from './components/aside'
import Container from './components/container'
import Header from './components/header'
import Footer from './components/footer'
import Main from './components/main'
import Row from './components/row'
import Col from './components/col'
import Button from './components/button'

const components = [
  Alert,
  Aside,
  Container,
  Header,
  Footer,
  Main,
  Row,
  Col,
  Button,
]

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  Alert,
  Aside,
  Container,
  Header,
  Footer,
  Main,
  Row,
  Col,
  Button
}
