/* Automatically generated by './build/bin/build-entry.js' */

import Alert from './components/Alert'
import Aside from './components/Aside'
import Container from './components/Container'
import Header from './components/Header'
import Footer from './components/Footer'
import Main from './components/Main'

const components = [
  Alert,
  Aside,
  Container,
  Header,
  Footer,
  Main,
]

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  Alert,
  Aside,
  Container,
  Header,
  Footer,
  Main
}
